name: on Pull Request
run-name: ${{ github.actor }} on Pull Request
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v4
      - name: installing node
        uses: actions/setup-node@v4
        with: 
          node-version: 'latest'
      - name: cache deps
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: node_modules-${{ hashFiles('**/yarn.lock')}}
      - name: install dependencies
        run: yarn ci
      - name: lint app
        run: yran run lint
        working-directory: ./my-app
  prettier:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: get repository code
        uses: actions/checkout@v4
      - name: cache deps
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: node_modules-${{ hashFiles('**/yarn.lock')}}
      - name: install dependencies
        run: yarn ci
      - name: code formatting
        run: yarn run format
        working-directory: ./my-app
  deployment:
    runs-on: ubuntu-latest
    needs: [eslint, prettier]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: yarn ci && yarn run build
        working-directory: ./my-app
